version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  web:
    build: .
    command: /bin/sh
    user: devel
    volumes:
      - .:/home/devel/baukis2
    ports:
      - "3000:3000"
    depends_on:
      - db
    tty: true
